// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query_collection

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID               int64
	Title            string
	Description      string
	CreatedByUserID  int64
	AssignedToUserID pgtype.Int8
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamp
}
